robindort.preorder_timer.controller:
    resource: ../src/Controller
    type: annotation



Als Dankeschön für Ihr Abonnement unseres Newsletters erhalten Sie von uns einen Rabattgutschein, den Sie bei Ihrem nächsten Einkauf einlösen können.

Ihr Gutscheincode lautet:

DorjiNews24


Wir freuen uns darauf, Ihnen zukünftig unsere neuesten Sushi-Spezialitäten und Firmennews in Ihre Mailbox liefern zu dürfen.

Ihr Dorji Sushi To Go Team.


<noscript>
		
		{{insert_module::94}}
		
        <style>
            /* Hide the entire content when JavaScript is disabled */
            #wrapper {
                display: none;
            }
            
            /* Show a full-page alert with a message */
           .no-js-message {
                display: block;
                background-color: #e95208;
                color: white;
                padding: 20px;
                text-align: center;
                font-size: 18px;
                margin-top: 20px;
            }
        </style>
        <div class="no-js-message">
            JavaScript ist deaktiviert. Bitte aktivieren Sie JavaScript in Ihrem Browser um diese Seite bedienen zu können.
        </div>
    </noscript>